### ISSUE TITLE
[PatchChildren] 只有第一次改变的时候会更新dom,其他时候不会更新dom

### ISSUE THREAD

**Issue by liushuiyuan001** [cuixiaorui/mini-vue#3]
#### example/PatchChildren 组件第一次点击button时候会更新dom,再点击就不会更新dom了

发现 button的 onclick 会执行多次

      onclick: () => {
            isChange.value = !isChange.value
             console.error('isChange.value', isChange.value)
       }

@cuixiaorui

**Comment by cuixiaorui** [comment]
感谢

已经修复

是没有对比 props 时，两个匿名 click handler 是不相等的

导致注册了多次 click event 

触发了两次 click，所以看到的就是 view 没有发生改变
