### ISSUE TITLE
to:崔孝瑞

### ISSUE THREAD

**Issue by qingmiao1** [cuixiaorui/mini-vue#4]
一直支持你，关注你

**Comment by cuixiaorui** [comment]
感谢~

**Comment by qingmiao1** [comment]
你好，崔孝瑞，我想问你一个问题，
上次在看你的直播，是不是vue2升到vue3是一个命令解决的问题吗？如果是那个命名是什么呢？如果不是，那怎么升级呢？

**Comment by cuixiaorui** [comment]
可以看看官网的升级指南

https://v3.vuejs.org/guide/migration/introduction.html
