### ISSUE TITLE
通过reactive 创建 响应式对象并没有 被track .

### ISSUE THREAD

**Issue by plaknight** [cuixiaorui/mini-vue#43]
`const value = reactive({
  foo: 1,
});

const getter = computed(() => {
  return value.foo;
});

value.foo = 2 // 触发setter 函数时,会去调用trigger 函数,但发现 targetmap 是空的:原因就是 先要访问value.foo 才会track
console.log(getter.value)`

**Comment by cuixiaorui** [comment]
已经修复
