### ISSUE TITLE
patchKeyedChildren实现中,hostInsert的顺序问题

### ISSUE THREAD

**Issue by wgsheng06** [cuixiaorui/mini-vue#44]
```
for (let i = e2; i >= s2; i--) {

  // ...
  const anchor = i + 1 >= e2 + 1 ? null : c2[i + 1];
  hostInsert(newChild.el, container, anchor && anchor.el)
}
```
会不会造成插入节点是反向的？appendChild不是顺序插入的么

**Comment by wgsheng06** [comment]
const prevChildren = [
  h("div", { key: "a", id: "old-a" }, "a"),
  h("div", { key: "b", id: "old-b" }, "b"),
  h("div", { key: "c", id: "old-c" }, "c"),
];
const nextChildren = [
  h("div", { key: "e", id: "new-e" }, "e"),
  h("div", { key: "c", id: "new-c" }, "c"),
  h("div", { key: "b", id: "new-b" }, "b"),
  h("div", { key: "a", id: "new-a" }, "a"),
  h("div", { key: "f", id: "new-f" }, "f"),
];

测试用例顺序错误

**Comment by cuixiaorui** [comment]
diff 算法已经更新
问题已经修复
