### ISSUE TITLE
effect 方法收集依赖的时候默认会先触发监听函数一次

### ISSUE THREAD

**Issue by azhen98** [cuixiaorui/mini-vue#49]
猜测可能是为了兼容函数内有返回值的情况, 不太理解为什么需要先执行一次, 而不是等待依赖改变的时候触发呢

**Comment by viacooter** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by azhen98** [comment]
是不是因为为了满足纯函数相同输入相同输出的思想呢，每次都要有所输出

**Comment by azhen98** [comment]
在访问属性的时候把 effect函数和访问属性关联起来的 map. set(属性，effect函数)，如果不执行函数的话，就不会访问这个属性，从而无法把effect函数和属性绑定起来，，不知道理解的对不对
