### ISSUE TITLE
代码早里面的eslint报错需要怎么解决呢？

### ISSUE THREAD

**Issue by gjfei** [cuixiaorui/mini-vue#6]
![image](https://user-images.githubusercontent.com/33827314/106984786-2e5b5600-67a3-11eb-9ef0-0532f61c80fd.png)
clone vue-next 代码早里面的eslint报错需要怎么解决呢？
希望大佬告知一下

**Comment by ZxdNoob** [comment]
可以通过 ESLint 注释进行解决
