### ISSUE TITLE
readme 有张图片挂了

### ISSUE THREAD

**Issue by supperdsj** [cuixiaorui/mini-vue#83]
[关键函数调用图2](https://camo.githubusercontent.com/adb0a362da748a9c0ec1e010764c387271a0fa0018625773dde747cbe6a7a576/68747470733a2f2f757365722d676f6c642d63646e2e786974752e696f2f323032302f362f32322f313732646330383834306532356234323f773d3138313626683d39333426663d706e6726733d353530373232)

**Comment by jay6697117** [comment]
是的，崔老有空搞一下吧

**Comment by cuixiaorui** [comment]
已经修复哈
