### ISSUE TITLE
组件更新逻辑没写

### ISSUE THREAD

**Issue by linglingyun10** [cuixiaorui/mini-vue#9]
// 组件的更新
function updateComponent(n1, n2, container) {
  // TODO
  console.log("更新组件", n1, n2);
}

**Comment by cuixiaorui** [comment]
规划ing

**Comment by linglingyun10** [comment]
> 规划ing

ok，静候佳音

**Comment by cuixiaorui** [comment]
已经增加了组件的 props 对比逻辑

可以看看降额
